# Generated by Django 5.1.2 on 2025-02-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(blank=True)),
                ('autor', models.CharField(blank=True, max_length=255, verbose_name='Autor')),
                ('tipo', models.CharField(blank=True, max_length=255, verbose_name='Tipo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/')),
                ('linkgeral', models.URLField()),
                ('linkms', models.URLField(blank=True)),
            ],
        ),
    ]
